name: Node.js CI  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      # 检出代码  
      - name: Checkout code  
        uses: actions/checkout@v3  

      # 安装 pnpm  
      - name: Install pnpm  
        run: npm install -g pnpm  

      # 安装依赖并构建项目  
      - name: Install dependencies and build  
        run: |  
          pnpm install  
          pnpm run docs:build

      # 部署到 GitHub Pages  
      - name: Deploy to GitHub Pages  
        uses: peaceiris/actions-gh-pages@v3  
        with:  
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}  
          publish_branch: master  
          publish_dir: ./.vuepress/dist