name: Build and Deploy  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  

    steps:  
      # 检出代码（使用 actions/checkout@v3）  
      - name: Checkout  
        uses: actions/checkout@v3  

      # 使用 jenkey2011/vuepress-deploy 来构建和部署  
      - name: Build and Deploy with vuepress-deploy  
        uses: jenkey2011/vuepress-deploy@master  
        env:  
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  
          TARGET_REPO: weijieaaa/flux
          TARGET_BRANCH: master
          BUILD_SCRIPT: npm install -g pnpm && pnpm install && pnpm run docs:build 
          BUILD_DIR: .vuepress/dist 