name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: weijiaaa/flux
        TARGET_BRANCH: master
        BUILD_SCRIPT: pnpm install && pnpm docs:build
        BUILD_DIR: docs/.vuepress/dist/